mode: "test"

exp_prefix: "cvae"

base_dir: "results/{{exp_prefix}}"

checkpoint_dir: "{{base_dir}}/checkpoints"
checkpoint_file: best_model

framework:
    seed: 12345
    num_thread: 12
    num_gpu: 1

model:
    protocol: "cvae"
    latent_z_dim: 128
    hidden_dim: 64
    activation_func: tanh # {tanh, sigm, relu}

data:
    protocol: "cvae"
    input_depth_dim: 200 ## depth input: 100*2, state dim: 3
    input_state_dim: 3
    input_occumap_dim: [1, 256, 256] ## during test, we only downsample, not crop. Thus image sizes vary
    batch_size: 1
    crop_size: 0 ## means no crop
    downsample_factor: 4
    laser_max_range: 4
    n_ray: 100
    fov: 240
    occu_map_dir: "data/maps_test"

