mode: "test"

exp_prefix: "seq_cvae"
dir_prefix: "seq_cvae_lr0.001_local_depth"

base_dir: "results/{{dir_prefix}}"

checkpoint_dir: "{{base_dir}}/checkpoints"
checkpoint_file: best_model

vis: True
heatmap:
    gen: True
    num_data: 1024

framework:
    seed: 12345
    num_thread: 1
    num_gpu: 1

model:
    protocol: "seq_cvae"
    latent_z_dim: 128
    hidden_dim: 64
    activation_func: tanh # {tanh, sigm, relu}

data:
    protocol: "seq_cvae"
    input_depth_dim: 200 # depth input: 100*2, state dim: 3
    input_state_dim: 3
    input_occumap_dim: [1, 256, 256] ## during test, we only downsample, not crop. Thus image sizes vary
    batch_size: 1
    crop_size: 0 ## means no crop
    downsample_factor: 4
    laser_max_range: 4
    n_ray: 100
    fov: 240
    occu_map_dir: "data/maps_test"
    horizon: 10
    epsilon: 0.1
    world_coord_laser: True # {True, False} set True to use global depth measurement and False to use local depth measurement
