mode: "train"

exp_prefix: "seq_cvae"

base_dir: "results/{{exp_prefix}}"
log_dir: "log.jsonl"

checkpoint_dir: "{{base_dir}}/checkpoints"
checkpoint_file: best_model

vis: False

framework:
    seed: 12345
    num_thread: 12 # 12
    num_gpu: 1

model:
    protocol: "seq_cvae"
    latent_z_dim: 128
    hidden_dim: 64
    activation_func: tanh # {tanh, sigm, relu}

data:
    protocol: "seq_cvae"
    input_depth_dim: 200 # depth input: 100*2, state dim: 3
    input_state_dim: 3
    input_occumap_dim: [1, 256, 256]
    batch_size: 8
    crop_size: 256
    downsample_factor: 4
    laser_max_range: 4
    n_ray: 100
    fov: 240
    occu_map_dir: "data/maps_train"
    horizon: 16
    epsilon: 0.1
    world_coord_laser: True # {True, False} set True to use global depth measurement and False to use local depth measurement

train:
    num_epoch: 800
    lr: 0.001
    lr_ms: [500, 700]
    save_iter: 10
